02 file service
Alex775660/script-007-tasks pull request #2
Opened 2022-05-31 11:28 UTC by Alex775660

TASK 2

2022-06-01 08:01 UTC, maxx27 requested changes

2022-06-01 08:01 UTC, maxx27 commented on server/FileService.py
> +            elif not os.path.exists(self.root_dir + "\\" + path) and not autocreate:
или "/"
или os.path.join(self.root_dir, path)

2022-06-01 08:01 UTC, maxx27 commented on server/FileService.py
> +        except (RuntimeError, TypeError) as e:
Выкидываем исключение наверх, обработка будет выше

2022-06-01 08:01 UTC, maxx27 commented on server/FileService.py
> +            if not os.path.normpath(filename).startswith(os.path.dirname(filename)):
вынести в функцию (можно здесь, можно в utils/files.py)

2022-06-01 08:01 UTC, maxx27 commented on server/test_FileService.py
> +    def test_create_file(self):
проверить, что файла нет

2022-06-01 08:01 UTC, maxx27 commented on server/test_FileService.py
> +    def __init__(self):
лучше убрать init и использовать фикстуры и дать возможность pytest определять, что запускать (опция -k)

2022-06-01 08:01 UTC, maxx27 commented on server/test_FileService.py
> +    def __init__(self):
или
@pytest.fixture(scope='function')
def case_explicit():
    print('case_explicit: before test-case')
    yield {
        'user_data_dir': 'value',
        'user_data': 'value2',
    }
    print('case_explicit: after test-case')

    def test_explicit(self, case_explicit):
        assert case_explicit == 'CASE_EXPLICIT'
        case_explicit['user_data_dir']

или demo\tests\mypytests\test_7_get_data_class.py

2022-06-01 08:01 UTC, maxx27 commented on server/test_FileService.py
> +        assert list_files[0]['name'] == self.hello_txt
add assert len(list_files) == 1

2022-06-01 08:01 UTC, maxx27 commented on server/test_FileService.py
> +if __name__ == '__main__':
теперь это не нужно

2022-06-01 09:51 UTC, Alex775660 commented on server/FileService.py
> +            elif not os.path.exists(self.root_dir + "\\" + path) and not autocreate:
Сделано

2022-06-01 09:51 UTC, Alex775660 commented on server/FileService.py
> +        except (RuntimeError, TypeError) as e:
Сделано

2022-06-01 09:51 UTC, Alex775660 commented on server/FileService.py
> +            if not os.path.normpath(filename).startswith(os.path.dirname(filename)):
Сделано

2022-06-01 09:51 UTC, Alex775660 commented on server/test_FileService.py
> +    def test_create_file(self):
Сделано

2022-06-01 09:52 UTC, Alex775660 commented on server/test_FileService.py
> +    def __init__(self):
Сделано

2022-06-01 09:52 UTC, Alex775660 commented on server/test_FileService.py
> +        assert list_files[0]['name'] == self.hello_txt
Сделано

2022-06-01 09:52 UTC, Alex775660 commented on server/test_FileService.py
> +if __name__ == '__main__':
Сделано

2022-06-02 07:20 UTC, maxx27 commented
Done

2022-06-02 07:36 UTC, merged